package com.infoera.sportshub_inventory.enums;

public enum CompanyType {

    NONE,
    BOOKS_STATIONARY,
    ELECTRONICS,
    GARMENT_STORE,
    FOOD_RESTAURANT,
    HOTELS,
    JOBWORK_REPAIR,
    MOBILE_STORE,
    PHARMACY,
    PROFESSIONAL_SERVICES,
    SECURITY_SERVICES,
    TOUR_TRAVEL,
    TRADING_BUSINESS,
    GROCERY_STORE,
    MANUFACTURING,
    RETAIL_COUNTER,
    RETAIL_CHAIN_STORE,
    OPTICIAN,
    CONTRACTING_PROJECTS
}
